add: study about osi-7-layer
gdsc-ssu/cs-study pull request #1
Opened 2022-10-23 12:07 UTC by kanghyun98

## Summary
OSI 7계층 정리해보았습니다!
옛날에 정리했던거 보면서 다시 했는데, 잘못된 내용은 고치고 내용 보강도 해서 정리했습니다(스터디 하는 이유..!ㅋㅋㅋ)

근데 생각해보니 저번에 지민님이 찜 해놓으셨던 것 같은데.... 죄송합니다... 지워놓으셔서 깜빡했습니다..😢

## Check List
- [x] PR 제목을 commit convention에 맞게 작성
- [x] assignees 추가
- [x] reviewers 추가
- [ ] label 추가

2022-10-23 13:05 UTC, ChoiSangwon commented
너무 깔끔해요!!!!!!

2022-10-23 13:10 UTC, ChoiSangwon requested changes
각 레이어 설명 잘 되어 있어서 너무너무 좋은데 6계층에 예시가 추가되면 더 좋을거같아요!

2022-10-23 13:10 UTC, ChoiSangwon commented on 네트워크/OSI 7계층.md
> +### 6계층: Presentation Layer (표현 계층)
6계층에도 예시로 사용하는 프로토콜이 있으면 좋을거 같아요!
예를들어 jpeg나 gif 같은거요!

2022-10-24 09:03 UTC, yoo-jimin127 approved these changes
오우 ... 저 대신 너무 열심히 자세히 작성해주셔서 읽어보면서 도움이 더더 많이 되었어요!!! 🔥
계층별 정리와 내용들이 너무 잘 되어있어서 좋은 것 같아요 !!
너무 수고하셨습니다~~! 어프루브 ✅

2022-10-25 10:29 UTC, kanghyun98 commented on 네트워크/OSI 7계층.md
> +### 6계층: Presentation Layer (표현 계층)
@ChoiSangwon 앗 그러네요,, 5계층이랑 6계층 내용이 좀 부실했던 것 같습니다ㅠㅠ 내용 보충해서 다시 업로드 하겠습니다!

2022-10-25 15:12 UTC, ChoiSangwon approved these changes
고생하셨습니다!!!

2022-10-26 14:26 UTC, ballsona commented
오 학교 수업에선 TCP/IP 4계층만 구체적으로 다뤘어서 OSI 7계층이랑은 무슨 차이가 있나 궁금했었는데 강현님 덕분에 알게된 것 같아요!
수고하셨습니다~^^ 🐰

2022-10-26 14:26 UTC, ballsona approved these changes
오 학교 수업에선 TCP/IP 4계층만 구체적으로 다뤘어서 OSI 7계층이랑은 무슨 차이가 있나 궁금했었는데 강현님 덕분에 알게된 것 같아요!
수고하셨습니다~^^ 🐰

2022-10-29 03:17 UTC, Jun99uu commented
강현님 너무 멋있어요... 도움 많이 됐습니다😭😆

2022-11-02 14:53 UTC, Jun99uu approved these changes
❤️ 너무 깔끔한 정리인 것 같습니다 , , , , OSI 7계층 거의 매 학기마다 보는 것 같은데 매번 까먹...었지만 이제 안잊어버릴 것 같아요!!

2022-11-03 03:58 UTC, merged