add: os 내용 추가
gdsc-ssu/cs-study pull request #15
Opened 2022-11-09 06:50 UTC by shs6626

## Summary
OS 관련 내용 정리
## Check List
- [o] PR 제목을 commit convention에 맞게 작성
- [o] assignees 추가
- [o] label 추가

2022-11-10 09:37 UTC, yoo-jimin127 requested changes
💔 : 오 ... ㅋㅋㅋㅋ 책 한권 읽는 줄 알았을 정도로 정리 잘 되어있네요!
본 풀리퀘의 assignees가 강현님으로 되어있으신데, 
해당 내용 작업자이신 홍석님으로 변경 요청드립니다!!
긴 내용 정리하시느라 수고 많으셨습니다!

2022-11-10 09:44 UTC, yoo-jimin127 reviewed
❤️‍🩹 : 몇가지 피드백 및 수정사항 전달드립니다!!
이건 반영 하셔도, 안하셔도 전혀 상관 없지만..! 
너무 좋은 자료 정리해주셔서,,ㅎㅎ
내용 종결어미를 `~입니다.` or `~다.` 중 하나로 통일해주시면 더욱 좋을 것 같아요!!

2022-11-10 09:44 UTC, yoo-jimin127 commented on 운영체제/IT-infra.md
> +# 1주차 [~2장]
❤️‍🩹 : 최상단 헤더 내용을 IT-infra와 관련된 내용이라면 챕터명 혹은 관련 주제 요약 타이틀로 변경해주시면 더 좋을 것 같습니다!

2022-11-10 09:44 UTC, yoo-jimin127 commented on 운영체제/IT-infra.md
> +![Untitled](1%E1%84%8C%E1%85%AE%E1%84%8E%E1%85%A1%20%5B~2%E1%84%8C%E1%85%A1%E1%86%BC%5D%20a9371720355041a0abf7e97f163f39dc/Untitled.png)
💔 : 이미지가 깨진 것 같아요! 강현님께서 cs 노션에 작성해주신 깃허브에 이미지 불러오기 방법 참고하셔서 수정해주시면 좋을 것 같습니다 ☺️

2022-11-10 09:44 UTC, yoo-jimin127 commented on 운영체제/IT-infra.md
> +- 서버 대수를 늘릴 수 있어서 확작성이 높다
💔 : 오타 있는 것 같습니다..!!

2022-11-13 04:53 UTC, ChoiSangwon approved these changes
❤️ 인프라 관련해서 전체적으로 정리해주신거 같아서 좋습니다!

2022-11-19 12:00 UTC, Jun99uu approved these changes
❤💔 너무 깔끔하고 읽기 좋게 정리해주셔서... 너모 좋았습니다!! 지민님께서 리뷰해주신 부분만 쵸큼 수정해주시면 될 것 같아효!!!!! 고생하셔씀니다ㅎㅎ

2022-11-25 06:44 UTC, ballsona requested changes
❤️ 오 인프라 관련한 부분은 접할 기회가 많이 없었는데, 홍석님 덕에 대략적인 개념들을 접할 수 있어서 좋았던 것 같아요! 
💔 다만 다음 PR로 올리신 네트워크 기초 파일이 요기에도 commit 된 것 같아요.. ㅜㅜ 이 `os/three` 브랜치에서 `네트워크/Network 기초.md` 파일 삭제하시고 삭제 커밋 올리시면 해결될 것 같습니다!
💔 PR 제목을 통일성 있게 `add: study about infra` 이런식으로 변경해주시면 좋을 것 같아요! PR 상단의 `Edit` 버튼 통해서 수정 부탁드립니다 :) 

어려운 내용 정리하시느라 수고하셨습니다 !

2022-11-25 06:44 UTC, ballsona commented on 운영체제/IT-infra.md
> +CPU가 데이터를 사용하면 캐시에 저장되게 되는데, 데이터가 캐시 됨과 동시에 주기억장치 또는 디스크로 기입되는 방식을 지원하는 구조의 캐시이다. 즉, 캐시와 메모리 둘다에 업데이트를 해버리는 방식이다.장점 : 캐시와 메모리에 업데이트를 같이 하여, 데이터 일관성을 유지할 수 있어서 안정적이다.단점 : 속도가 느린 주기억장치 또는 보조기억장치에 데이터를
❤️‍🩹 장단점 부분에 줄바꿈이 있으면 좋을것 같네요!

2023-03-05 16:48 UTC, closed without merging