what is internet?
gdsc-ssu/cs-study pull request #17
Opened 2022-11-11 08:31 UTC by sebbbin

컴퓨터 네트워크 하향식 접근 (컴학전공책) 1.1장 정리

## Summary

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] label 추가

2022-11-14 04:05 UTC, yoo-jimin127 commented on 인터넷이란.md
> +과목: 네트워크
💔 : 이 내용들은 PR과 노션에 있어서 따로 없어도 괜찮을 것 같아요!!☺️

2022-11-14 04:05 UTC, yoo-jimin127 commented on 인터넷이란.md
> +전 세계적으로 수십억 개의 컴퓨팅 장치를 연결하는 컴퓨터 네트워크 → 애플리케이션에 서비스를 제공하는 인파라스트럭쳐
💔 : 오타 있는 것 같습니다..!

2022-11-14 04:05 UTC, yoo-jimin127 commented on 인터넷이란.md
> +    ![Untitled](%E1%84%8B%E1%85%B5%E1%86%AB%E1%84%90%E1%85%A5%E1%84%82%E1%85%A6%E1%86%BA%E1%84%8B%E1%85%B5%E1%84%85%E1%85%A1%E1%86%AB%208c871e17b9c54231a2e50fbcbf33f30c/Untitled.png)
💔 : 이미지가 깨지는 것 같아요!! 강현님께서 노션에 작성해주신 이미지 삽입 글대로 올려주시면 될 것 같습니다!! ☺️

2022-11-14 04:05 UTC, yoo-jimin127 commented on 인터넷이란.md
> +패킷 교환과 TCP/IP는 무엇인가? 라우터는 무엇인가? 인터넷에는 어떤 종류의 통신 링크가 있는가? 분산 애플리케이션은 무엇인가? 어떻게 토스터와 기상 센서가 인터넷에 연결될 수 있는가?
❤️‍🩹 : 기술질문 내용도 같이 다뤄주셔서 너무 좋네요!!
혹시 한 줄보다 리스트 형식으로
- 패킷 교환과 TCP/IP는 무엇인가? 
- 라우터는 무엇인가? 
- 인터넷에는 어떤 종류의 통신 링크가 있는가? 
- 분산 애플리케이션은 무엇인가? 
- 어떻게 토스터와 기상 센서가 인터넷에 연결될 수 있는가?

위처럼 작성해주시는건 어떨까요!!?

2022-11-19 12:52 UTC, sebbbin commented on 인터넷이란.md
> +과목: 네트워크
앗 같이 옮겨졌네요 ! 감사합니다 ㅎㅎ

2022-11-19 12:53 UTC, sebbbin commented on 인터넷이란.md
> +전 세계적으로 수십억 개의 컴퓨팅 장치를 연결하는 컴퓨터 네트워크 → 애플리케이션에 서비스를 제공하는 인파라스트럭쳐
@yoo-jimin127 꼼꼼히 감사드립니다 ..👍✨

2022-11-19 12:54 UTC, sebbbin commented on 인터넷이란.md
> +패킷 교환과 TCP/IP는 무엇인가? 라우터는 무엇인가? 인터넷에는 어떤 종류의 통신 링크가 있는가? 분산 애플리케이션은 무엇인가? 어떻게 토스터와 기상 센서가 인터넷에 연결될 수 있는가?
@yoo-jimin127 덕분에 가독성 올라간것 같아요 👍✨😊

2022-11-19 14:16 UTC, yoo-jimin127 commented on 인터넷이란.md
> +패킷 교환과 TCP/IP는 무엇인가? 라우터는 무엇인가? 인터넷에는 어떤 종류의 통신 링크가 있는가? 분산 애플리케이션은 무엇인가? 어떻게 토스터와 기상 센서가 인터넷에 연결될 수 있는가?
앜ㅋㅋㅋㅋ 하나하나 답글까지,,,💖 문서 내용 읽기 좋게 정리랑 수정 잘 해주셨네요!! 고생 많으셨어요 ㅎㅎㅎ!!

2022-11-19 14:16 UTC, yoo-jimin127 approved these changes

2022-11-20 14:43 UTC, Jun99uu approved these changes
❤ 사족 없이 깔끔한 문장들이네요!! 편하게 읽을 수 있었습니다. 고생하셨습니다!!!!

2022-11-20 14:46 UTC, Jun99uu commented on 인터넷이란.md
> +### 주요 의문들 !
이 의문들은 나중에 해결해주시는거죠...??ㅋㅋㅋㅋㅋㅋㅋ

2022-11-25 07:10 UTC, ballsona approved these changes
오 뭔가 인터넷 이라는게 당연한 존재?이지만 누가 갑자기 저 붙잡고 `what is internet` 라고 물어보면 제대로 답해주지 못할것 같은.. 그런 기본 내용들을 덕분에 복습하게 되어 좋았던 것 같아요! 
💔 PR 제목을 통일성있게 `add : study about Internet` 이런식으로 수정 부탁드립니다 :) 
정리하시느라 수고하셨어요 !!

2022-11-25 07:10 UTC, ballsona commented on 인터넷이란.md
> +- 인터넷 구성요소
❤️‍🩹 요부분 노션글에서 보니까 Toggle 안에 멋진 이미지가 들어가 있던데.. 이곳에도 첨부해주시면 너무 좋을것 같아요! 이미지 첨부는 [이글](https://www.notion.so/fcca5be834b8438d92f1556a3ccf6ecd) 보면서 하시면 어렵지 않을거에요! (물론 저의 개인적 희망사항이니까 안하셔도 문제없슴다 !!)

2022-11-27 18:25 UTC, binisnull commented
❤️: 컴퓨터의 기본이지만,,,사실은 잘 모르고있는,,, 몰라서는 안되는,,, 지식들 잘 정리해주셔서 감사해요!! 지식 상기시킬 수 있었습니당🫶🏻

2022-11-29 08:55 UTC, binisnull approved these changes
❤️: 컴퓨터의 기본이지만,,,사실은 잘 모르고있는,,, 몰라서는 안되는,,, 지식들 잘 정리해주셔서 감사해요!! 지식 상기시킬 수 있었습니당🫶🏻

2022-12-24 04:14 UTC, kanghyun98 approved these changes
❤️ 학습하면서 들었던 의문점까지 정리한 점이 인상 깊어요! 추후에 적어주신 부분들에 대해서도 학습하고 공유해주시면 더 좋을 것 같아요👍👍

2022-12-24 04:14 UTC, kanghyun98 commented on 인터넷이란.md
> +테스크톱 PC, 리눅스 워크스테이션, 서버 등 전통적인 장치
❤️‍🩹 오타 있습니다!

2023-01-07 12:44 UTC, kanghyun98 requested changes
💔 작성하신 파일을 네트워크 폴더로 옮겨주셔야 해요!
글 양식 작업도 부탁드릴게요!

2023-03-05 17:09 UTC, closed without merging