add : 네트워크 기초
gdsc-ssu/cs-study pull request #22
Opened 2022-11-13 08:38 UTC by shs6626

## Summary
네트워크 용어
## Check List
- [x] PR 제목을 commit convention에 맞게 작성
- [x] assignees 추가
- [x] label 추가

2022-11-14 03:46 UTC, yoo-jimin127 approved these changes
❤️ : 네트워크에서 중요하게 사용되는 용어와 개념들 잘 정리해주셔서 너무 좋네요!! 수고하셨습니다 ㅎㅎ

2022-11-14 03:49 UTC, yoo-jimin127 commented on 네트워크/Network 기초.md
> +![Untitled](Network%207ebb5025d00f4578ae2cfa3bc7a03dac/Untitled.png)
💔 : 이미지가 깨져요..!! 강현님께서 올려주신 깃허브에 이미지 올리는 방법 참고 부탁드립니다!!☺️

2022-11-14 03:49 UTC, yoo-jimin127 commented on 네트워크/Network 기초.md
> +![Untitled](Network%207ebb5025d00f4578ae2cfa3bc7a03dac/Untitled%201.png)
❤️‍🩹 : 이미지 또는 작성 시 참고하신 자료 링크도 함께 올려주시면 더 좋을 것 같아요!! ☺️

2022-11-14 06:14 UTC, shs6626 commented on 네트워크/Network 기초.md
> +![Untitled](Network%207ebb5025d00f4578ae2cfa3bc7a03dac/Untitled%201.png)
아 감사합니당!

2022-11-26 02:41 UTC, Jun99uu approved these changes
❤ 지민님이 말씀해주신 이미지 깨지는 문제만 수정해주시면 될 것 같아요!
고생하셨습니다!!!

2022-12-24 04:19 UTC, kanghyun98 approved these changes
❤️  네트워크 기초 지식에 대한 정리가 잘 되어있는 것 같아요!
❤️‍🩹 글 양식 작업 진행해주시면서 이미지랑 오타 관련 작업까지 같이 진행해주시면 좋을 것 같습니다😃

2022-12-24 04:19 UTC, kanghyun98 commented on 네트워크/Network 기초.md
> +ISP(internet Service Provider 인터넷 서비스 제공자 ex. KT, LG U+
❤️‍🩹 괄호 닫아주셔야 될 것 같아요!

2023-02-26 08:15 UTC, kanghyun98 requested changes
이미지 깨진 것 수정해서 올려주시면 감사하겠습니다:)

2023-03-05 16:49 UTC, closed without merging