edge network
gdsc-ssu/cs-study pull request #23
Opened 2022-11-13 17:40 UTC by sebbbin

종단 시스템, 접속 시스템, 다양한 전송매체, 이더넷과 와이파이

## Summary

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] label 추가

2022-11-15 01:35 UTC, yoo-jimin127 requested changes
💔 : 세빈님!! 마크다운 문서 내용이 누락된 것 같아요! 확인 부탁드립니다!!

2022-11-19 12:31 UTC, sebbbin commented
> 💔 : 세빈님!! 마크다운 문서 내용이 누락된 것 같아요! 확인 부탁드립니다!!

수정해보려 했는데 ㅠㅠ 잘 안돼서 밑에 새로 파일 추가했었는데 다시 업로드 하는편이 나을까요?

2022-11-19 13:19 UTC, sebbbin commented
> 💔 : 세빈님!! 마크다운 문서 내용이 누락된 것 같아요! 확인 부탁드립니다!!

@yoo-jimin127 성공한것 같아요!!

2022-11-26 02:54 UTC, Jun99uu approved these changes
❤ 전 맨날 PR 올릴 때 마다 드립치고싶어서 안절부절하는데... 이런 사족 없이 깔끔한 문장들.. 너무 조하효...............
카테고리(?)를 나눠서 헤더로 묶으면 더 예쁜 문서가 되지 않을까 싶슘다!!!

2022-11-26 02:54 UTC, Jun99uu commented on 네트워크/edge network .md
> +호스트
❤️🩹 약간 이런 부분 # 세개짜리 헤더로 감싸면 가독성이 더 좋아질 것 같은 릐끰적인릐끰이 듭니당!

2022-12-24 04:02 UTC, JjungminLee approved these changes
❤: 우아.. 저 엣지 네트워크를 처음 들어봤는데 세빈님께서 예시별로 설명을 해주셔서 어떤건지 쪼금 감이 잡혔어요! 깔끔한 정리 잘봤습니당~ 수고하셨어요!

2023-01-26 07:38 UTC, yoo-jimin127 approved these changes

2023-02-26 08:19 UTC, kanghyun98 requested changes
오타 수정 및 글 양식 작업 부탁드리겠습니다!

2023-02-26 08:19 UTC, kanghyun98 commented on 네트워크/edge network .md
> +    **공유 바송 매체이다. 특히 헤드엔드가 보낸 모든 패킷이 모든 링크의 다운스트림 채널을 통해 모든 가정으로 전달된다.
💔 bold 처리 문제, 오타 있습니다!

2023-03-05 15:35 UTC, yoo-jimin127 commented
@sebbbin 어랏 세빈님 !!! 요거 수정사항 다 수정해주신 것 같은데, PR 머지가 아니라 아예 닫아버리신 것 같아서..!!
Reopen해서 머지 진행하겠습니당!

2023-03-05 15:35 UTC, merged