add : 도커 기본
gdsc-ssu/cs-study pull request #37
Opened 2022-11-27 13:48 UTC by shs6626

## Summary

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] label 추가

2022-11-27 15:48 UTC, sebbbin reviewed
엄청 상세하게 잘 써주셔서 이미지 수정되면 다시 또 공부하러 와야 겠습니당 ‼👍 도커에 대해 처음 접해보지만 상세히 알 수 있는 기회였어요 😊 감사합니다

2022-11-27 15:48 UTC, sebbbin commented on 네트워크/docker.md
> +![Untitled](%E1%84%83%E1%85%A9%E1%84%8F%E1%85%A5%E1%84%85%E1%85%B3%E1%86%AF%20%E1%84%8B%E1%85%B5%E1%84%8B%E1%85%AD%E1%86%BC%E1%84%92%E1%85%A1%E1%86%AB%20%E1%84%8F%E1%85%A5%E1%86%AB%E1%84%90%E1%85%A6%
💔 : 이미지가 깨져서 https://www.notion.so/fcca5be834b8438d92f1556a3ccf6ecd 여기 참고하시면 좋을 것 같아요 💪😊

2022-11-27 15:48 UTC, sebbbin commented on 네트워크/docker.md
> +docker ps : 실행중인 컨테이너 목록을 확
❤️‍🩹 : 확 다음에 뭔가 더 있을 것 같아서 조심스레 남겨보아요 ..!

2022-12-03 15:31 UTC, yoo-jimin127 requested changes
💔 : 도커 기본 사용법에 대해 배우고 싶었는데 홍석님께서 자세하게 정리해주셔서 꼼꼼히 읽으며 공부하다가 본의 아니게 리뷰를 많이 남겨둔 것 같습니다..ㅎㅎㅎ
내용 정리 정말 자세하고 꼼꼼하게 해주셔서 도커 사용에 대해 잘 알게 된 것 같아요!
노션에서 내보내기 하신 것 같아서 첨부해주신 이미지가 대부분 제대로 보이지 않는 것 같아요..!🥲
그리고 도커 명령어 부분 코드블록으로 감싸주시면 더더더 가독성도 내용도 좋은 자료가 될 것 같습니다!!
긴 내용 정리해주시느라 수고하셨어요! 덕분에 도커 열공하고 갑니다 ㅎㅎ

2022-12-03 15:31 UTC, yoo-jimin127 commented on 네트워크/docker.md
> +이미지는 컨테이너를 생성할 때 필요한 요소로 컨테이너의 목적에 맞는 바이너리와 의존성이 설치되어 있습니다. 여러 개의 계층으로 도니 바이너리 파일로 존재합니다
💔 : 여기 오타 있는 것 같습니다..!!

2022-12-03 15:31 UTC, yoo-jimin127 commented on 네트워크/docker.md
> +docker run image
❤️‍🩹 : 명령어 부분들을 코드블록으로 감싸주시는건 어떨까요?? 가독성이 더 좋아질 것 같습니다!!
ex) `docker run image`

2022-12-03 15:31 UTC, yoo-jimin127 commented on 네트워크/docker.md
> +docker container prune : 중지된 모든 컨테이너 삭
💔 : 오타 있는 것 같습니다!

2022-12-03 15:31 UTC, yoo-jimin127 commented on 네트워크/docker.md
> +docker exec my-nginx env : my-nginx 컨테이너 환경변수 확인하
💔 : 오타 있는 것 같아요 ..ㅎㅎ!!

2022-12-03 15:31 UTC, yoo-jimin127 commented on 네트워크/docker.md
> +publish 옵션은 실제 포트를 바인
❤️‍🩹 : 실제 포트를 **바인딩** 일까요…???

2022-12-03 15:31 UTC, yoo-jimin127 commented on 네트워크/docker.md
> +호스트 운영체제의 로그 저장 경
💔 : 오타 있습니다!

2022-12-03 15:31 UTC, yoo-jimin127 commented on 네트워크/docker.md
> +💡 FROM : 베이스 이미지 사
💔 : 오타 있는 것 같숨다…!

2022-12-08 11:18 UTC, Jun99uu approved these changes
❤️‍🩹 저도 수업에서 도커 배우고있는데 너무 반가운 내용이네요!!!
지민님이 말씀해주신 부분들만 수정해주시면 좋을 것 같아요!! :)

2022-12-24 19:16 UTC, ballsona approved these changes
❤️ 와 이번에 수업시간에 도커 쓸때마다 명령어 맨날 까먹어서 구글링하고 그랬는데.. 요기에 정리가 이렇게 잘 되어있을 줄이야.. ㅠㅠ 정리하느라 수고하셨습니다!
+도커 사용하게 될때 다시 보고 싶은 문서인 만큼, 요기 첨부되어있는 이미지들도 어떤것들인지 궁금해지네요!!

2023-02-26 08:20 UTC, kanghyun98 requested changes
글 양식 작업 및 이미지 깨진 것 수정 부탁드려요!

2023-03-05 16:50 UTC, closed without merging