add : study about LoadBalancing
gdsc-ssu/cs-study pull request #42
Opened 2022-12-18 23:25 UTC by JjungminLee

## Summary
HTTP 스터디나 시험준비하면서 공부했던 로드밸런싱에 대해 정리해봤습니다!
로드밸런싱 정의 -> 동작방식 -> 알고리즘 -> 종류 그리고 GSLB와 CDN까지 공부해봤어요!
L3체크랑 CDN 사진은 제가 직접 일러레로 만든거라 쓰시고 싶은 분들은 자유롭게 쓰시면 됩니당~! 
## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] label 추가

2022-12-20 01:48 UTC, ChoiSangwon approved these changes
❤️ http스터디 할때 같이 공부했던 내용이여서 더 반갑네요! 
 로드밸런싱을 aws등으로 사용하면서 그냥 당연히 "트래픽을 분산해주는 역할"이라고만 알고있었는데 깊게 팔수록 여러내용들이 많은것 같네요
분량도 많고 정리도 정말 잘하신거같습니다. 고생하셨습니다!!!!!!

2022-12-23 05:24 UTC, yoo-jimin127 approved these changes
♥️ : 우와… 직접 이미지까지 제작해주셨다니 … 로드밸런싱 관련해서 정민님 깔끔한 글 덕분에 공부 정말 잘 하고 가요!! 상황 별로 직접 이미지 만들어주셔서 줄글과 함께 이해하기 너무 좋은 것 같습니다ㅠㅠ 최고예요!!

2022-12-25 15:10 UTC, sebbbin approved these changes
♥️ : 하나의 과목에서 배운 내용을 다른 CS개념들과 확장시켜 공부할 수 있어서 더욱 도움되었어요 ! 다른 개념들도 이렇게 학습해서 더 깊게 알아봐야겠어요

2023-01-07 12:18 UTC, kanghyun98 approved these changes
❤️ 여러 중요 네트워크 개념들을 모두 다루셔서 리뷰하면서 상당히 많이 배울 수 있었습니다!

내용적인 부분에서 이해가 되지 않는 질문 하나 남겼는데, 답변 주시면 감사하겠습니다😄

2023-01-07 12:18 UTC, kanghyun98 commented on 네트워크/LoadBalancing.md
> +![Untitled](https://user-images.githubusercontent.com/85864699/208324606-5fce605e-0741-4fb5-b882-5900b65a987c.png)
❤️‍🩹 이미지 사용할때 작은 꿀팁인데 이미지 태그를 사용하고 `style="zoom:50%;"` 이렇게 속성값 추가해주면 이미지 크기 조절할 수 있어요!
아래처럼 하면 되는데 리뷰에서는 적용 안되네여,,ㅋㅋ
<img src="https://user-images.githubusercontent.com/85864699/208324606-5fce605e-0741-4fb5-b882-5900b65a987c.png" alt="Untitled" style="zoom:50%;" />

2023-01-07 12:18 UTC, kanghyun98 commented on 네트워크/LoadBalancing.md
> +4. 별도 DNS 서버는 로드 배런서의 IP주소를 메인 DNS 서버에게 알려준다.
💔 오타 있습니다!

2023-01-07 12:18 UTC, kanghyun98 commented on 네트워크/LoadBalancing.md
> +3. 메인 DNS서버는 로드 밸런서의 IP(Virtual IP)주소를 메인 DNS 서버에게 알려준다.
💔 3번에서 메인 DNS 서버가 메인 DNS 서버에게 VIP를 알려준다는게 뭔가 말이 이상한 것 같아요,, 
아니면 제가 잘 이해를 못하는 부분이 있는걸까요?

2023-01-25 16:09 UTC, kanghyun98 requested changes
지난 리뷰 때 수정해야할 부분이 있었는데, 아무 생각없이 Approve를 던졌네여,,
한번 보시고 수정하신 다음에 리뷰 재요청 주시면 감사하겠습니다:)

2023-03-04 15:19 UTC, Jun99uu approved these changes
❤️ 사실 수업 때도 듣고.. 프로젝트하면서 여러 번 들은 내용인데도 매번 새하얗게 잊어버렸어요...

2023-03-04 15:19 UTC, Jun99uu commented on 네트워크/LoadBalancing.md
> +        |  | GSLB | DNS |
❤️ 역시 항상 이렇게 테이블로 정리해주시는거 너무 좋아요,,,

2023-03-06 01:56 UTC, merged