add : study about DNS & DHCP
gdsc-ssu/cs-study pull request #56
Opened 2022-12-31 22:31 UTC by JjungminLee

## Summary
저번에 로드밸런싱을 공부했었는데 거기에서 본 DNS를 좀 더 확장해서 DHCP까지 곁들여 공부해봤습니다!
2023년 새해에 일어나자 마자 한 일이 CS Storage네요!ㅎㅎ 모두 새해 복 많이 받으세요~!! 😀😁

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] label 추가

2023-01-06 23:01 UTC, yoo-jimin127 approved these changes
♥️ : 우와 … 지금까지 봤던 CS 내용 중 가장 어렵고 처음 접하는 내용이 많았던 것 같은데 그럼에도 너무 정리를 잘 해주셔서 여러번 읽고 꼭꼭 이해하고 싶은 개념인 것 같아요! 정민님 정말 정리 잘 하시네요 …. 최고예요🥺👍

2023-01-08 14:46 UTC, sebbbin approved these changes
❤: 원래 새해 첫날 듣는 노래대로 한 해를 보낸다는 것처럼, 새해 처음 한 것이 CS Storage인만큼 올해 많이 저장해봐요 ㅎㅎ ! 정리는 매번 믿고보는,, 네트워크는 개인적으로 줄임말로 된 단어들이 너무 많아서 헷갈리는데 다시 한 번 복습하고 가요 ~ 새해복 많이 받으세요 !

2023-01-15 07:07 UTC, kanghyun98 requested changes
❤️ 주제랑 내용이 너무 좋아서 재밌게 읽었어요!!

💔 오타 하나 있어서 request changes 날리지만.. 수정하고 리뷰 재요청 해주시면 바로 어프루브 때리겠습니다:)

2023-01-15 07:07 UTC, kanghyun98 commented on 네트워크/DNS&DHCP.md
> +    - 대표적으로 ISP DNS 서버와 Cloud flare와 같은 Public DNS서버가 있다.
❤️ 와 DNS 서버가 이런 구조로 되어있다는걸 처음 알았네여..ㅋㅋㅋㅋㅋ
그림이랑 설명 덕분에 이해하기 쉬웠습니다👍🏼👍🏼

2023-01-15 07:07 UTC, kanghyun98 commented on 네트워크/DNS&DHCP.md
> +- Roun Robin이란 DNS 서버 구성방식 중 하나로, Domain에 대한 IP요청 쿼리시, Round Robin 방식으로 IP주소를 반환한다.
💔 오타 하나 있습니다!

2023-01-15 07:07 UTC, kanghyun98 commented on 네트워크/DNS&DHCP.md
> +        - 로드 밸런서에서 실시간으로 connection 수를 관리하거나 각 서버에게 주기적으로 알려주는 것이 필요하다.
그러면 현재 DNS 서버에서 운용하는 방식은 Round Robin이고, 그냥 RR만 쓰면 말씀해주신 단점들이 있으니깐 해결책으로 제시해주신 방법들과 같이 사용된다고 이해하면 되는걸까요..?

2023-01-20 22:25 UTC, JjungminLee commented on 네트워크/DNS&DHCP.md
> +- Roun Robin이란 DNS 서버 구성방식 중 하나로, Domain에 대한 IP요청 쿼리시, Round Robin 방식으로 IP주소를 반환한다.
넵 고칠게요!

2023-01-21 02:44 UTC, kanghyun98 approved these changes

2023-01-21 02:45 UTC, merged