add : study about Monotone Stack
gdsc-ssu/cs-study pull request #60
Opened 2023-01-08 14:40 UTC by sebbbin

요즘 알고리즘 공부를 하면서 새롭게 배운 개념이에요 알고리즘의 세계란 넓고도 넓은,, 도움이 되실까 싶어 관련 문제 번호도 넣어봤습니다 !

## Summary

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] label 추가

2023-01-15 07:27 UTC, kanghyun98 requested changes
❤️ 오 그냥 stack을 응용한 풀이 방법인줄 알았는데, Monotone Stack이라는 이름이 있었군여.. 하나 배워갑니다!

2023-01-15 07:27 UTC, kanghyun98 commented on Monotone Stack.md
> +작성일시: January 8, 2023 11:16 PM
💔 이 부분은 빼주시는게 좋을 것 같습니다!

2023-01-21 08:45 UTC, Jun99uu approved these changes
❤ 오호 이런게 있었군뇨..!! 모노톤 스택은 처음 봤어요! 고생하셨습니다!!!

2023-01-29 14:40 UTC, ballsona approved these changes
❤️ 오옹 세빈님 덕분에 처음 알게된 개념이에요! 백준 번호도 친절하게 써주셔서 시간될 때 한번 적용해서 풀어보고 싶네요! 정리하느라 수고하셨습니다! 👍  :) 
(+ 생소한 개념인지라 시각적인 자료도 넣어주셨음 넘 좋았을 것 같아요! 물론 지금도 완벽합니다 ㅎㅎ❤️)

2023-02-04 14:22 UTC, yoo-jimin127 approved these changes
❤️‍🩹 : 오!! 처음 들어보는 유형의 알고리즘인 것 같아요!! 혹시 개념 이해가 더 잘 될 수 있도록 예제코드가 있다면 추가해주시는 건 어떨까용??

2023-03-05 11:15 UTC, sebbbin commented on Monotone Stack.md
> +작성일시: January 8, 2023 11:16 PM
감사합니다 뺐어요 !! 
저도 여러종류가 있어서 놀랐어요 ,, 엄청난 확장성😂

2023-03-05 17:03 UTC, merged