add : study about Adapter
gdsc-ssu/cs-study pull request #66
Opened 2023-01-22 07:34 UTC by JjungminLee

## Summary
제가 요즘 어쩌다 안드로이드 개발을 하게 되었는데 어댑터라는 디자인 패턴을 알게 되었습니다! 
안드로이드에서 뷰를 만들때 어댑터가 굉장히 중요한 역할을 하는 것 같아서 한번 정리해봤어요!
재미로 읽어주세요! (저도 시작한지 얼마 안돼서 정확하지 않을 수 있답니다..!)

## Check List
- [ ] PR 제목을 commit convention에 맞게 작성
- [ ] assignees 추가
- [ ] label 추가

2023-01-25 06:44 UTC, ballsona approved these changes
❤️ 오 제가 전공시간에 이 Adapter 패턴 접하고 100% 이해를 못하고 넘어갔었는데, 정민님이 적어주신 설명이랑 예시 보고 이해를 제대로 하게 된 것 같아요! 안드로이드 예시도 보여주시니까 흥미롭네요 🤭 정리하시느라 수고하셨습니다:)

2023-01-25 16:33 UTC, kanghyun98 requested changes
❤️ 사실 어댑터 패턴을 처음 들어봤는데, 이미지도 많고 예시도 좋아서 이해하기 쉬운 정리글인 것 같아요!
❤️‍🩹 이미지 사이즈 조절을 조금 하면 더 좋을 것 같아요!

2023-01-25 16:33 UTC, kanghyun98 commented on 디자인패턴/Adapter.md
> +- 안드로이드에서의 어댑터는 **뷰(Client)**와 **데이터 셋(Adaptee)**를 연결해주는 역할을 한다.
💔 bold 처리가 안됐어요!

2023-02-05 01:22 UTC, yoo-jimin127 approved these changes
❤️ : 오와우 .. 어댑터 패턴이 이런 의미였군요 ..? 예제 코드에 이미지까지 첨부해주셔서 너무 잘 설명해주신 덕에 이해가 정말 잘 된 것 같아요 !! 정민님 자료는 항상 깔끔해서 넘 좋네유 ..

2023-02-06 00:48 UTC, ChoiSangwon approved these changes
❤️ 오 제가 디자인패턴을 잘 몰라서 어댑터 패턴이 뭔가 했는데 정말 "어댑터"역할을 해주는 거였네요!
저는 호환성이 없는 라이브러리나 객체를 사용할 때 원본 코드를 수정하고는 했는데 하면서도 이게 맞나? 했던적이 있는데 다음에는 어댑터를 만들어서 적용해 봐야겠습니다!
~~물론 그게 훨씬 어려울수도 있겠지만..?~~

2023-03-04 15:22 UTC, Jun99uu approved these changes
❤️ 와 코틀린 찍먹할 때 웬만한 뷰들은 다 어댑터로 구현함에도 개념 공부할 생각을 안해봤는데...
이게 패턴에서 기인한 것이었군뇨... 최고임니다..

2023-03-06 01:41 UTC, merged